server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # SPA-fallback: любые маршруты отдаём в index.html, роутинг — на клиенте
    location / {
        try_files $uri $uri/ /index.html;
    }
}
